version: 2.1

orbs:
  node: circleci/node@4.7
  katalon-studio: katalon/katalon-studio@23.0.11

workflows:
  start: 
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
