version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6
  katalon-studio: katalon/katalon-studio@23.0.11

jobs:
  run_unittests:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm run test
  deploy_staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  run_tests:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: cd test_katalon && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/TS_Staging" -executionProfile="default" -browserType="Chrome (headless)"
  deploy:
    docker:
      - image: cimg/base:2022.04
    steps:
      - run:
          name: Trigger host deployment
          command: |
            curl $DEPLOY_HOOK
            echo 'Triggered deploy'

workflows:
  build-run-and-test:
    jobs:
      - run_unittests
      - deploy_staging:
          requires:
            - run_unittests
          # filters:
          #   branches:
          #     only:
          #       - main
      - katalon-studio/run:
          version: "latest"
          command_arguments: '-browserType="Chrome" -retry=2 -statusDelay=15 -projectPath="/tmp/project/test_katalon" -testSuitePath="Test Suites/TS_Staging"'
          requires:
            - deploy_staging
      - deploy:
          requires:
            - katalon-studio/run
            # - run_unittests
          # filters:
          #   branches:
          #     only:
          #       - main
