version: 2.1

orbs:
  node: circleci/node@4.7
  katalon-studio: katalon/katalon-studio@23.0.11

jobs:
  run_tests:
    docker:
      - image: cimg/node:14.15.3
    steps:
    - checkout
    - run:
        name: Install npm dependencies
        command: |
          npm install --save
    - run:
        name: Start node server
        command: |
          npm start
        background: true
    - run:
        name: Run Unit Tests
        command: |
          sleep 20
          npm run test

workflows:
  build-run-and-test: 
    jobs:
      - run_tests
